---
- hosts: localhost
  gather_facts: false
  become: true
  tasks:
    - ping:
    - file:
        path: new_file
        state: touch
    - name: installing basic vim
      apt:
        name: vim
        state: latest
